---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  roles:
      - geerlingguy.swap    
      - marshyon.k8squickbase
  tasks:
    - name: Set k8s master hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
    - name: Common packages
      apt:
        pkg:
          - curl
          - software-properties-common
          - python3-pip
          - net-tools
          - vim
          - etcd-client 
          - build-essential
        state: latest
        update_cache: true

    - name: bash k8s config file 
      ansible.builtin.copy:
        content: |
                  source <(kubectl completion bash)
                  alias k=kubectl
                  alias c=clear
                  complete -F __start_kubectl k
        dest: /root/.bashrc_kubernetes
        owner: root
        group: root
        mode: '0755'

    - name: Ensure terminal settings are in bashrc
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        regexp: 'bash_kubernetes'
        line: '. ~/.bashrc_kubernetes'

    - name: Ensure color prompt is set in bashrc
      ansible.builtin.lineinfile:
        path: /root/.bashrc
        regexp: 'force_color_prompt=yes'
        line: 'force_color_prompt=yes'







- hosts: k8smaster
  become: true
  vars_files:
    - vars/default.yml
  roles:
      - marshyon.k8squickmaster

      
- hosts: k8sworker01
  become: true
  vars_files:
    - vars/default.yml
  roles:
      - marshyon.k8squickworker





